name: Check

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm lint:ts

      - name: Format
        run: pnpm format:check

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test:ci

      - name: Upload coverage
        uses: codecov/codecov-action@v3
