name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Lint TypeScript
        run: yarn lint:ts
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
